### ISSUE TITLE
Hello message from Initiator

### ISSUE THREAD

**Issue by ThibaudREY** [ThibaudREY/conferly#40] opened 2019-10-24 06:40 UTC
Send a hello message from pc initiator (not session initiator) to allow non-initiator to send messages

**Comment by ThibaudREY** [comment] 2019-11-04 21:01
This message should include peer state such as mic toggle, video toggle, ...
And should hence be bidirectional.

**Comment by ghost** [comment] 2019-11-21 21:58
Closing this as we know that the issue is not related to send a message from pc but from "timing" "latency".

We should open a new issue.

**Closed as completed by ghost** 2019-11-21 21:58 UTC
